kind: Deployment
apiVersion: extensions/v1beta1 
metadata:  
  name: nginx 
  namespace: nginx-test
  labels:
    name: nginx
spec:  
  replicas: 1 
  template: 
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx