kind: Deployment
apiVersion: extensions/v1beta1 
metadata:   #资源的元数据/属性
  name: nginx #资源的名字，在同一个namespace中必须唯一
  namespace: nginx-test
  labels:
    name: nginx
spec:   #specification of the resource content 指定该资源的内容
 replicas: 1 #副本数量
  template:  #这里Pod的定义
    metadata:
      labels:
       app: nginx
    spec:
      containers:
      - name: nginx  #容器的名字
        image: nginx